<a href="https://colab.research.google.com/github/Zenith1618/LLM/blob/main/StableLM_%26_Orca_LLMs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers ctransformers accelerate

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 34.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.0/280.0 kB 30.7 MB/s eta 0:00:00


In [2]:
!pip install sentencepiece

In [13]:
import torch
from pprint import pprint

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

## StableLM

StableLM-Base-Alpha-3B-v2 is a 3 billion parameter decoder-only language model pre-trained on diverse English datasets. This model is the successor to the first StableLM-Base-Alpha-3B model, addressing previous shortcomings through the use of improved data sources and mixture ratios.

This is an example of using the generative capabilities of the model

In [5]:
from transformers import AutoModelForCausalLM, AutoTokenizer

In [6]:
model_name = "stabilityai/stablelm-base-alpha-3b-v2"

In [7]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
model_name,
trust_remote_code=True,
torch_dtype="auto",
)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/235 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.11M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/104 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


config.json:   0%|          | 0.00/706 [00:00<?, ?B/s]

configuration_stablelm_alpha.py:   0%|          | 0.00/4.76k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/stabilityai/stablelm-base-alpha-3b-v2:
- configuration_stablelm_alpha.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


modeling_stablelm_alpha.py:   0%|          | 0.00/26.7k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/stabilityai/stablelm-base-alpha-3b-v2:
- modeling_stablelm_alpha.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


model.safetensors.index.json:   0%|          | 0.00/16.4k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.96G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [8]:
model.cuda()

StableLMAlphaForCausalLM(
  (transformer): StableLMAlphaModel(
    (embed): Embedding(50432, 2560)
    (layers): ModuleList(
      (0-31): 32 x DecoderLayer(
        (norm): LayerNorm((2560,), eps=1e-05, elementwise_affine=True)
        (attention): Attention(
          (qkv_proj): Linear(in_features=2560, out_features=7680, bias=False)
          (out_proj): Linear(in_features=2560, out_features=2560, bias=False)
          (rotary_emb): RotaryEmbedding()
        )
        (mlp): MLP(
          (gate_proj): Linear(in_features=2560, out_features=13824, bias=False)
          (out_proj): Linear(in_features=6912, out_features=2560, bias=False)
          (act): SiLU()
        )
      )
    )
    (final_norm): LayerNorm((2560,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=2560, out_features=50432, bias=False)
)

In [15]:
inputs = tokenizer("The weather is always wonderful", return_tensors="pt").to(device)

In [19]:
tokens = model.generate(
**inputs,
max_new_tokens=300,
temperature=0.75,
top_p=0.95,
do_sample=True,
)

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


In [20]:
tokens

tensor([[  510,  8588,   310,  1900,  9386,   275,   378, 22779,  5002,    13,
           285,   436,  7408,   369,   642,  6517,    15,   844,  2335,   247,
         33111,   432, 22699, 48535, 37964,   281, 30173,   255, 13409,   285,
           840,   247,  1685,   281,   418,   410,   936,   835,   359,  2335,
           247, 24928,   281,   253,  2419,   835,   359,   651,  3297,   323,
           253,  1735,   767,  3618,    15,   187,   510,  2419,    13,   347,
           368,   476,   923,    13,   310,  5389,    15,  1707,   403,  1264,
          1781, 37445,   285,   247,  1781,  3811,  2316,   342,   247, 39696,
            15,   187,   510,  8576,   310,   247, 26540,   457,    84,  7156,
             2,   380,  1859,   432,   253,  3811,  2316,    13,  8576,    13,
         17552,  2316,    13,   285,   767, 37445,   310, 22936,    15,   187,
          1231, 11580,   247,  4564,   273,   253,  5389, 29780,    13,   533,
           581,   273,   776,  7583,   369,   253,  

In [21]:
pprint(tokenizer.decode(tokens[0], skip_special_tokens=True))

('The weather is always wonderful in Baja California, and this trip was no '
 'exception. We took a ferry from Puerto Vallarta to Mazatlan and then a bus '
 'to Loreto where we took a taxi to the house where we would stay for the next '
 'two weeks.\n'
 'The house, as you can see, is beautiful. There are three large bedrooms and '
 'a large living room with a fireplace.\n'
 'The kitchen is a chef’s dream! The view from the living room, kitchen, '
 'dining room, and two bedrooms is spectacular.\n'
 'We visited a couple of the beautiful beaches, but one of our favorite was '
 'the one next to the house. We went back there a couple of times.\n'
 'The beach was so beautiful and the waves were so powerful. I took a few '
 'photos of the waves and the sunset.\n'
 'We also enjoyed visiting the local market.\n'
 'We were there at the end of March, and the weather was perfect for the '
 'beach.\n'
 'We had a great time, and we enjoyed our time in Loreto.\n'
 'If you’re planning a trip to Loreto

In [22]:
torch.cuda.empty_cache()

## Orca mini 3B

This is an example of prompt answer generation

In [23]:
from transformers import LlamaForCausalLM, LlamaTokenizer

In [24]:
model_path = 'psmathur/orca_mini_3b'
tokenizer = LlamaTokenizer.from_pretrained(model_path)
model = LlamaForCausalLM.from_pretrained(
model_path, torch_dtype=torch.float16, device_map='auto',
)

tokenizer_config.json:   0%|          | 0.00/700 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/534k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/208 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.98M [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


config.json:   0%|          | 0.00/553 [00:00<?, ?B/s]

pytorch_model.bin.index.json:   0%|          | 0.00/21.8k [00:00<?, ?B/s]

pytorch_model-00001-of-00003.bin:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

pytorch_model-00002-of-00003.bin:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

pytorch_model-00003-of-00003.bin:   0%|          | 0.00/3.72G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()


generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

In [25]:
prompt = "Write about ISRO and his achievements"

In [26]:
tokens = tokenizer.encode(prompt)
tokens = torch.LongTensor(tokens).unsqueeze(0)
tokens = tokens.to(device)

In [27]:
instance = {'input_ids': tokens,'top_p': 1.0, 'temperature':0.2, 'generate_len': 512, 'top_k': 30}

In [29]:
length = len(tokens[0])
with torch.no_grad():
 response = model.generate(
 input_ids=tokens,
 max_length=length+instance['generate_len'],
 top_p=instance['top_p'],
 temperature=instance['temperature'],
 top_k=instance['top_k'],
 use_cache=True,
 do_sample=True,
 )

In [30]:
response

tensor([[    1, 14734,   562,  3461,  2784,   291,   492, 14013, 31843,    13,
         23959, 31876, 31829,  2138,  4938, 31844,  3461,  2784, 31844,   470,
           985,  2259,  7872,   289,   266,  1497, 31876, 31829,  2138,  1221,
         31843,  1591,   287,   619,   758, 12187, 14013,   322,   266,  4540,
           287,   266,   712,  3162, 10890, 31844,   308,   505, 31435,   846,
         31844,   288, 31822, 31853, 31877, 31888, 31880, 31843,   672,   393,
           260,  2259, 19477,   288,  2600, 31876, 31829,  2138,  1221,   362,
           357,  8163,   266,  1497, 31876, 31829,  4852,   684,   266,  2138,
          2253, 31843,    13,  1921,  2784,   470,   615,   604,  4181,   329,
           869,   590,  2259, 14013, 31844,  1224,   266,  4540,   287,   266,
           712,  3162, 23130, 31844, 18871,  4708, 31844,   288, 31822, 31853,
         31877, 31886, 31852, 31844,   266,   712,  3162, 10890,   289,   333,
          5090,   288, 16619,  1163,   266,  4556, 3

In [33]:
output = response[0][length:]
output

tensor([31843,    13, 23959, 31876, 31829,  2138,  4938, 31844,  3461,  2784,
        31844,   470,   985,  2259,  7872,   289,   266,  1497, 31876, 31829,
         2138,  1221, 31843,  1591,   287,   619,   758, 12187, 14013,   322,
          266,  4540,   287,   266,   712,  3162, 10890, 31844,   308,   505,
        31435,   846, 31844,   288, 31822, 31853, 31877, 31888, 31880, 31843,
          672,   393,   260,  2259, 19477,   288,  2600, 31876, 31829,  2138,
         1221,   362,   357,  8163,   266,  1497, 31876, 31829,  4852,   684,
          266,  2138,  2253, 31843,    13,  1921,  2784,   470,   615,   604,
         4181,   329,   869,   590,  2259, 14013, 31844,  1224,   266,  4540,
          287,   266,   712,  3162, 23130, 31844, 18871,  4708, 31844,   288,
        31822, 31853, 31877, 31886, 31852, 31844,   266,   712,  3162, 10890,
          289,   333,  5090,   288, 16619,  1163,   266,  4556, 31844, 16783,
        31854, 31853, 31849, 31844,   288, 31822, 31853, 31877, 

In [34]:
result = tokenizer.decode(output, skip_special_tokens=True)

In [36]:
pprint(result)

('.\n'
 "India's space agency, ISRO, has made significant contributions to the "
 "country's space program. One of its most notable achievements is the launch "
 'of the first Indian satellite, Aryabhata, in 1975. This was a significant '
 "milestone in India's space program as it marked the country's entry into the "
 'space age.\n'
 'ISRO has also been responsible for many other significant achievements, '
 'including the launch of the first Indian spacecraft, Rohini, in 1980, the '
 'first Indian satellite to be placed in orbit around the Earth, IRS-1A, in '
 '1981, and the first Indian satellite to be launched into polar orbit, '
 'IRS-1B, in 1983.\n'
 'In addition to these achievements, ISRO has also been responsible for the '
 'launch of many other spacecraft, including the Chandrayaan-1 mission to the '
 'Moon, the Mangalyaan mission to Mars, and the INSAT-3D mission to provide '
 'communication and weather data to the Indian region.\n'
 "ISRO has also been at the forefront of I

In [37]:
torch.cuda.empty_cache()